import collections.abc as abc
from io import BytesIO as StringIO
from typing import Any, Optional

PY3: bool

def abstractproperty(func: Any): ...

MAXSIZE: Any
imap = map

def b(s: Any): ...
def bytes_from_hex(h: Any): ...
def iteritems(d: Any): ...
def itervalues(d: Any): ...
def reraise(exctype: Any, value: Any, trace: Optional[Any] = ...) -> None: ...
def reraise_instance(exc_instance: Any, trace: Optional[Any] = ...) -> None: ...
def _unicode(s: str) -> str: ...
text_type = str
string_type = str
integer_types = int
